module.exports = {
  entry: "articles",
  output: "blog",
  author: "Peter Yuan",
  name: "How To",
  github: "https://github.com/GitHubJiKe/howto",
  datetime: {
    use: true,
    format: "YYYY/MM/DD HH:mm:ss",
  },
  dev: {
    port: 8080,
  },
  showdownConfig: {
    strikethrough: true,
    underline: true,
    tasklists: true,
    tables: true,
    tablesHeaderId: true,
    splitAdjacentBlockquotes: true,
    smartIndentationFix: true,
    simplifiedAutoLink: true,
    simpleLineBreaks: true,
    requireSpaceBeforeHeadingText: true,
    parseImgDimensions: true,
    openLinksInNewWindow: true,
    omitExtraWLInCodeBlocks: true,
    ghMentions: true,
    excludeTrailingPunctuationFromURLs: true,
    encodeEmails: true,
    emoji: true,
    backslashEscapesHTMLTags: true,
  },
};
